### ISSUE TITLE
Runtime wgpu related error

### ISSUE THREAD

**Issue by pando85** [tindleaj/miso#6]
```bash
$ cargo run --release
warning: unused label
  --> src/player.rs:53:13
   |
53 |             'player: loop {
   |             ^^^^^^^
   |
   = note: `#[warn(unused_labels)]` on by default

warning: variant is never constructed: `Stop`
  --> src/player.rs:15:5
   |
15 |     Stop,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

    Finished release [optimized] target(s) in 0.61s
     Running `target/release/miso`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/agil/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: RecvError', <unnamed>', ', src/player.rssrc/player.rssrc/player.rs:' panicked at 'thread 'thread '<unnamed><unnamed>thread 'thread '' panicked at '' panicked at '<unnamed>called `Result::unwrap()` on an `Err` value: RecvError<unnamed>called `Result::unwrap()` on an `Err` value: RecvError' panicked at '', ', src/player.rs' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorthread 'src/player.rscalled `Result::unwrap()` on an `Err` value: RecvError<unnamed>', ' panicked at ':', src/player.rscalled `Result::unwrap()` on an `Err` value: RecvError57src/player.rs:', ::57src/player.rs2357::
:235723
:
23
:57:23
:57:23
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/player.rs:57:23
thread '57<unnamed>thread ':' panicked at '<unnamed>called `Result::unwrap()` on an `Err` value: RecvError' panicked at '57', called `Result::unwrap()` on an `Err` value: RecvError:src/player.rs', 23:src/player.rs
57::5723:
23
:23
```

**Comment by pando85** [comment]
I had to install Vulkan drivers to get it working.
After getting `vulkaninfo` working I could get miso running correctly.

**Comment by pando85** [comment]
Probably the best approach could be to make GPU rendering optional.
